# Generated by Django 3.0.3 on 2020-04-02 18:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meter', '0002_auto_20200402_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reads',
            fields=[
                ('reads_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_value', models.BooleanField()),
                ('reactive_value', models.BooleanField()),
                ('date', models.DateField()),
                ('meter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meter.Meter')),
            ],
        ),
    ]
