# Generated by Django 3.0.3 on 2020-04-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reads',
            name='active_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reads',
            name='reactive_value',
            field=models.FloatField(),
        ),
    ]
