# Generated by Django 3.0.3 on 2020-04-02 16:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('contract_id', models.UUIDField(editable=False)),
                ('period_id', models.UUIDField(editable=False)),
            ],
        ),
    ]
