# Generated by Django 3.0.3 on 2020-04-02 20:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('contract_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.Contract')),
                ('period_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='period.Period')),
            ],
        ),
    ]
