# Generated by Django 3.0.3 on 2020-04-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0001_initial'),
        ('contract', '0002_auto_20200402_1844'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='contract_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.Contract'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='period.Period'),
        ),
    ]
