# Generated by Django 3.0.3 on 2020-04-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_client_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(default='2001-01-01'),
            preserve_default=False,
        ),
    ]
