# Generated by Django 3.0.3 on 2020-04-02 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transmodel',
            fields=[
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('serie', models.CharField(max_length=15)),
                ('primary_voltage', models.FloatField()),
                ('secundary_voltage', models.FloatField()),
                ('stream_output', models.FloatField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('depth', models.FloatField()),
            ],
        ),
    ]
