# Generated by Django 3.0.3 on 2020-04-02 20:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subestation', '0001_initial'),
        ('transmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('trans_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=30)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=30)),
                ('subestation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subestation.Subestation')),
                ('transmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transmodel.Transmodel')),
            ],
        ),
    ]
