# Generated by Django 3.0.3 on 2020-04-02 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metmodel',
            fields=[
                ('metmodel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('weight', models.FloatField()),
                ('precision', models.FloatField()),
                ('frequency', models.FloatField()),
                ('power_factor', models.FloatField()),
                ('rated_current', models.FloatField()),
            ],
        ),
    ]
