export const FETCH_USER = 'fetchUser'
export const FETCH_USERS = 'fetchUsers'
export const CREATE_USER = 'createUser'
export const DELETE_USER = 'deleteUser'
export const UPDATE_USER = 'updateUser'
export const LOGIN = 'login'
export const LOGOUT = 'logout'