# Generated by Django 3.0.3 on 2020-04-02 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(editable=False, max_length=30)),
                ('national_id', models.CharField(max_length=19)),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
                ('role', models.CharField(max_length=15)),
            ],
        ),
    ]
