# Generated by Django 3.0.3 on 2020-04-02 20:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('predial', models.FloatField()),
                ('address', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Client')),
                ('meter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meter.Meter')),
            ],
        ),
    ]
