# Generated by Django 3.0.3 on 2020-04-02 16:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transformer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('meter_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metmodel', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
                ('transformer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transformer.Transformer')),
            ],
        ),
    ]
