# Generated by Django 3.0.3 on 2020-04-02 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metmodel', '0001_initial'),
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='metmodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metmodel.Metmodel'),
        ),
    ]
